-- Seed Coding Questions (Technical Challenges)
-- Curated set of ~50 DSA interview problems (Blind 75 / NeetCode-style)

USE careerpilot;

-- Idempotent-ish seed: keep existing rows; only insert missing slugs.
-- Note: For fully idempotent seeding across all MySQL versions, use a separate migration strategy.

INSERT IGNORE INTO coding_questions
  (title, slug, description, difficulty, topics, company_tags, examples, constraints, expected_approach, hints, test_cases, solution_template, source)
VALUES
-- Arrays
('Two Sum', 'two-sum',
 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\nReturn the answer in any order.',
 'easy',
 '["Arrays","Hashing"]',
 '["Google","Amazon","Meta"]',
 '[{"input":"nums=[2,7,11,15], target=9","output":"[0,1]"},{"input":"nums=[3,2,4], target=6","output":"[1,2]"}]',
 '2 <= nums.length <= 1e4\n-1e9 <= nums[i], target <= 1e9\nExactly one solution exists.',
 'Use a hash map from value -> index. For each number x, check whether (target-x) was seen before; if yes, return those indices.',
 '["Hash map lookup for complement in O(1)"]',
 '[{"input":"[2,7,11,15]\\n9","output":"[0,1]"},{"input":"[3,2,4]\\n6","output":"[1,2]"}]',
 '{"python":"def twoSum(nums, target):\\n    # return [i,j]\\n    pass","javascript":"function twoSum(nums, target){\\n  // return [i,j]\\n}","java":"public int[] twoSum(int[] nums, int target){\\n  // return new int[]{i,j};\\n  return null;\\n}","cpp":"vector<int> twoSum(vector<int>& nums,int target){\\n  // return {i,j};\\n}"}',
 'curated'),

('Best Time to Buy and Sell Stock', 'best-time-to-buy-and-sell-stock',
 'You are given prices where prices[i] is the stock price on day i. Choose one day to buy and a later day to sell. Return the maximum profit (or 0 if none).',
 'easy',
 '["Arrays","Greedy"]',
 '["Amazon","Microsoft"]',
 '[{"input":"prices=[7,1,5,3,6,4]","output":"5"},{"input":"prices=[7,6,4,3,1]","output":"0"}]',
 '1 <= prices.length <= 1e5\n0 <= prices[i] <= 1e4',
 'Scan once while tracking the minimum price so far. At each price, compute profit = price - minPrice and keep the maximum.',
 '["Track min so far; update max profit"]',
 '[{"input":"[7,1,5,3,6,4]","output":"5"},{"input":"[7,6,4,3,1]","output":"0"}]',
 '{"python":"def maxProfit(prices):\\n    pass","javascript":"function maxProfit(prices){\\n}","java":"public int maxProfit(int[] prices){\\n  return 0;\\n}","cpp":"int maxProfit(vector<int>& prices){\\n  return 0;\\n}"}',
 'curated'),

('Contains Duplicate', 'contains-duplicate',
 'Given an integer array nums, return true if any value appears at least twice; otherwise return false.',
 'easy',
 '["Arrays","Hashing"]',
 '["Amazon","Adobe"]',
 '[{"input":"nums=[1,2,3,1]","output":"true"},{"input":"nums=[1,2,3,4]","output":"false"}]',
 '1 <= nums.length <= 1e5',
 'Use a hash set to track seen elements; if a number is already in the set, return true.',
 '["Hash set membership check"]',
 '[{"input":"[1,2,3,1]","output":"true"},{"input":"[1,2,3,4]","output":"false"}]',
 '{"python":"def containsDuplicate(nums):\\n    pass","javascript":"function containsDuplicate(nums){\\n}","java":"public boolean containsDuplicate(int[] nums){\\n  return false;\\n}","cpp":"bool containsDuplicate(vector<int>& nums){\\n  return false;\\n}"}',
 'curated'),

('Product of Array Except Self', 'product-of-array-except-self',
 'Given nums, return answer where answer[i] is product of all nums except nums[i]. Do it in O(n) without division.',
 'medium',
 '["Arrays","Prefix Sum"]',
 '["Amazon","Meta","Microsoft"]',
 '[{"input":"nums=[1,2,3,4]","output":"[24,12,8,6]"}]',
 '2 <= nums.length <= 1e5\n-30 <= nums[i] <= 30',
 'Compute prefix products and suffix products. answer[i] = prefix[i-1] * suffix[i+1]. Optimize to O(1) extra by reusing output array.',
 '["Two passes: prefix then suffix"]',
 '[{"input":"[1,2,3,4]","output":"[24,12,8,6]"}]',
 '{"python":"def productExceptSelf(nums):\\n    pass","javascript":"function productExceptSelf(nums){\\n}","java":"public int[] productExceptSelf(int[] nums){\\n  return null;\\n}","cpp":"vector<int> productExceptSelf(vector<int>& nums){\\n}"}',
 'curated'),

('Maximum Subarray', 'maximum-subarray',
 'Find the contiguous subarray with the largest sum and return its sum.',
 'medium',
 '["Arrays","Dynamic Programming"]',
 '["Amazon","Microsoft"]',
 '[{"input":"nums=[-2,1,-3,4,-1,2,1,-5,4]","output":"6"}]',
 '1 <= nums.length <= 1e5\n-1e4 <= nums[i] <= 1e4',
 'Kadane’s algorithm: track best subarray sum ending at i. bestEnd = max(nums[i], bestEnd+nums[i]); answer = max(answer,bestEnd).',
 '["Kadane\\u2019s DP on the fly"]',
 '[{"input":"[-2,1,-3,4,-1,2,1,-5,4]","output":"6"}]',
 '{"python":"def maxSubArray(nums):\\n    pass","javascript":"function maxSubArray(nums){\\n}","java":"public int maxSubArray(int[] nums){\\n  return 0;\\n}","cpp":"int maxSubArray(vector<int>& nums){\\n  return 0;\\n}"}',
 'curated'),

-- Strings
('Valid Anagram', 'valid-anagram',
 'Given strings s and t, return true if t is an anagram of s.',
 'easy',
 '["Strings","Hashing"]',
 '["Amazon","Google"]',
 '[{"input":"s=\\"anagram\\", t=\\"nagaram\\"","output":"true"},{"input":"s=\\"rat\\", t=\\"car\\"","output":"false"}]',
 '1 <= s,t.length <= 5e4',
 'Count character frequencies (array of 26 for lowercase) or use a hash map; compare counts for s and t.',
 '["Frequency counting"]',
 '[{"input":"anagram\\nnagaram","output":"true"},{"input":"rat\\ncar","output":"false"}]',
 '{"python":"def isAnagram(s, t):\\n    pass","javascript":"function isAnagram(s, t){\\n}","java":"public boolean isAnagram(String s, String t){\\n  return false;\\n}","cpp":"bool isAnagram(string s,string t){\\n  return false;\\n}"}',
 'curated'),

('Valid Parentheses', 'valid-parentheses',
 'Given a string s containing only (), {}, [], determine if the input string is valid.',
 'easy',
 '["Strings","Stack & Queue"]',
 '["Amazon","Google"]',
 '[{"input":"s=\\"()[]{}\\"","output":"true"},{"input":"s=\\"(]\\"","output":"false"}]',
 '1 <= s.length <= 1e4',
 'Use a stack. Push opening brackets; on closing bracket, check top matches the type. Stack must be empty at end.',
 '["Stack matching with map"]',
 '[{"input":"()[]{}","output":"true"},{"input":"(]","output":"false"}]',
 '{"python":"def isValid(s):\\n    pass","javascript":"function isValid(s){\\n}","java":"public boolean isValid(String s){\\n  return false;\\n}","cpp":"bool isValid(string s){\\n  return false;\\n}"}',
 'curated'),

('Longest Substring Without Repeating Characters', 'longest-substring-without-repeating-characters',
 'Given a string s, return the length of the longest substring without repeating characters.',
 'medium',
 '["Strings","Hashing","Sliding Window"]',
 '["Amazon","Bloomberg"]',
 '[{"input":"s=\\"abcabcbb\\"","output":"3"},{"input":"s=\\"bbbbb\\"","output":"1"}]',
 '0 <= s.length <= 5e4',
 'Sliding window with two pointers and a map from character -> last seen index. Move left pointer past duplicates.',
 '["Two-pointer sliding window"]',
 '[{"input":"abcabcbb","output":"3"},{"input":"bbbbb","output":"1"}]',
 '{"python":"def lengthOfLongestSubstring(s):\\n    pass","javascript":"function lengthOfLongestSubstring(s){\\n}","java":"public int lengthOfLongestSubstring(String s){\\n  return 0;\\n}","cpp":"int lengthOfLongestSubstring(string s){\\n  return 0;\\n}"}',
 'curated'),

-- Linked List
('Reverse Linked List', 'reverse-linked-list',
 'Given the head of a singly linked list, reverse the list and return the new head.',
 'easy',
 '["Linked List"]',
 '["Amazon","Meta"]',
 '[{"input":"head=[1,2,3,4,5]","output":"[5,4,3,2,1]"}]',
 '0 <= n <= 5000',
 'Iterative pointer reversal: keep prev, curr; at each step, save next, point curr.next to prev, advance.',
 '["Iterative pointer reversal"]',
 '[{"input":"[1,2,3,4,5]","output":"[5,4,3,2,1]"}]',
 '{"python":"def reverseList(head):\\n    pass","javascript":"function reverseList(head){\\n}","java":"public ListNode reverseList(ListNode head){\\n  return null;\\n}","cpp":"ListNode* reverseList(ListNode* head){\\n  return nullptr;\\n}"}',
 'curated'),

('Linked List Cycle', 'linked-list-cycle',
 'Given head, determine if the linked list has a cycle.',
 'easy',
 '["Linked List","Two Pointers"]',
 '["Amazon","Microsoft"]',
 '[{"input":"head=[3,2,0,-4], pos=1","output":"true"},{"input":"head=[1], pos=-1","output":"false"}]',
 '0 <= n <= 1e4',
 'Floyd’s cycle detection: slow moves 1, fast moves 2. If they meet, a cycle exists.',
 '["Floyd\\u2019s tortoise and hare"]',
 '[{"input":"[3,2,0,-4]\\n1","output":"true"},{"input":"[1]\\n-1","output":"false"}]',
 '{"python":"def hasCycle(head):\\n    pass","javascript":"function hasCycle(head){\\n}","java":"public boolean hasCycle(ListNode head){\\n  return false;\\n}","cpp":"bool hasCycle(ListNode* head){\\n  return false;\\n}"}',
 'curated'),

-- Binary Search
('Binary Search', 'binary-search',
 'Given a sorted array nums and target, return index if found, else -1.',
 'easy',
 '["Binary Search","Arrays"]',
 '["Google","Amazon"]',
 '[{"input":"nums=[-1,0,3,5,9,12], target=9","output":"4"},{"input":"nums=[-1,0,3,5,9,12], target=2","output":"-1"}]',
 '1 <= nums.length <= 1e5',
 'Standard binary search with lo/hi pointers; shrink range until found or exhausted.',
 '["Classic binary search"]',
 '[{"input":"[-1,0,3,5,9,12]\\n9","output":"4"}]',
 '{"python":"def search(nums, target):\\n    pass","javascript":"function search(nums, target){\\n}","java":"public int search(int[] nums, int target){\\n  return -1;\\n}","cpp":"int search(vector<int>& nums,int target){\\n  return -1;\\n}"}',
 'curated');

INSERT IGNORE INTO coding_questions
  (title, slug, description, difficulty, topics, company_tags, examples, constraints, expected_approach, hints, test_cases, solution_template, source)
VALUES
-- Arrays / Hashing
('Merge Intervals', 'merge-intervals',
 'Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals and return the non-overlapping intervals that cover all the intervals in the input.',
 'medium',
 '["Arrays","Sorting"]',
 '["Google","Amazon"]',
 '[{"input":"intervals=[[1,3],[2,6],[8,10],[15,18]]","output":"[[1,6],[8,10],[15,18]]"}]',
 '1 <= intervals.length <= 1e4\nintervals[i].length == 2',
 'Sort intervals by start. Iterate and keep a current merged interval; if the next starts before current ends, extend the end, otherwise push current and start a new one.',
 '["Sort by start, then sweep to merge"]',
 '[{"input":"[[1,3],[2,6],[8,10],[15,18]]","output":"[[1,6],[8,10],[15,18]]"}]',
 '{"python":"def merge(intervals):\\n    pass","javascript":"function merge(intervals){\\n}","java":"public int[][] merge(int[][] intervals){\\n  return null;\\n}","cpp":"vector<vector<int>> merge(vector<vector<int>>& intervals){\\n}"}',
 'curated'),

('3Sum', '3sum',
 'Given an integer array nums, return all the unique triplets [nums[i], nums[j], nums[k]] such that i != j != k and nums[i] + nums[j] + nums[k] == 0.',
 'medium',
 '["Arrays","Two Pointers","Sorting"]',
 '["Meta","Amazon"]',
 '[{"input":"nums=[-1,0,1,2,-1,-4]","output":"[[-1,-1,2],[-1,0,1]]"}]',
 '3 <= nums.length <= 3000\n-1e5 <= nums[i] <= 1e5',
 'Sort the array. For each i, solve 2-sum on the suffix using two pointers while skipping duplicates to ensure unique triplets.',
 '["Sort + two pointers; skip duplicates"]',
 '[{"input":"[-1,0,1,2,-1,-4]","output":"[[-1,-1,2],[-1,0,1]]"}]',
 '{"python":"def threeSum(nums):\\n    pass","javascript":"function threeSum(nums){\\n}","java":"public List<List<Integer>> threeSum(int[] nums){\\n  return null;\\n}","cpp":"vector<vector<int>> threeSum(vector<int>& nums){\\n}"}',
 'curated'),

('Container With Most Water', 'container-with-most-water',
 'Given an integer array height, find two lines that together with the x-axis form a container that holds the most water. Return the maximum amount of water.',
 'medium',
 '["Arrays","Two Pointers"]',
 '["Google","Amazon"]',
 '[{"input":"height=[1,8,6,2,5,4,8,3,7]","output":"49"}]',
 '2 <= height.length <= 1e5\n0 <= height[i] <= 1e4',
 'Use two pointers at both ends. Compute area; move the pointer with the smaller height inward to potentially increase the limiting height.',
 '["Two pointers; move shorter side"]',
 '[{"input":"[1,8,6,2,5,4,8,3,7]","output":"49"}]',
 '{"python":"def maxArea(height):\\n    pass","javascript":"function maxArea(height){\\n}","java":"public int maxArea(int[] height){\\n  return 0;\\n}","cpp":"int maxArea(vector<int>& height){\\n  return 0;\\n}"}',
 'curated'),

('Longest Consecutive Sequence', 'longest-consecutive-sequence',
 'Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence. Must run in O(n).',
 'medium',
 '["Arrays","Hashing"]',
 '["Google","Amazon"]',
 '[{"input":"nums=[100,4,200,1,3,2]","output":"4"}]',
 '0 <= nums.length <= 1e5',
 'Put all numbers in a hash set. For each number that is the start of a sequence (x-1 not in set), extend forward while x+1 exists.',
 '["Hash set + expand from sequence starts"]',
 '[{"input":"[100,4,200,1,3,2]","output":"4"}]',
 '{"python":"def longestConsecutive(nums):\\n    pass","javascript":"function longestConsecutive(nums){\\n}","java":"public int longestConsecutive(int[] nums){\\n  return 0;\\n}","cpp":"int longestConsecutive(vector<int>& nums){\\n  return 0;\\n}"}',
 'curated'),

('Top K Frequent Elements', 'top-k-frequent-elements',
 'Given an integer array nums and an integer k, return the k most frequent elements.',
 'medium',
 '["Hashing","Arrays","Heap"]',
 '["Amazon","Meta"]',
 '[{"input":"nums=[1,1,1,2,2,3], k=2","output":"[1,2]"}]',
 '1 <= nums.length <= 1e5\n1 <= k <= number of unique elements',
 'Count frequencies with a hash map. Use a heap or bucket sort by frequency to extract the top k.',
 '["Frequency map; heap or buckets for top-k"]',
 '[{"input":"[1,1,1,2,2,3]\\n2","output":"[1,2]"}]',
 '{"python":"def topKFrequent(nums, k):\\n    pass","javascript":"function topKFrequent(nums, k){\\n}","java":"public int[] topKFrequent(int[] nums, int k){\\n  return null;\\n}","cpp":"vector<int> topKFrequent(vector<int>& nums,int k){\\n}"}',
 'curated'),

('Subarray Sum Equals K', 'subarray-sum-equals-k',
 'Given an array of integers nums and an integer k, return the total number of subarrays whose sum equals k.',
 'medium',
 '["Arrays","Hashing","Prefix Sum"]',
 '["Google","Amazon"]',
 '[{"input":"nums=[1,1,1], k=2","output":"2"}]',
 '1 <= nums.length <= 2e4\n-1000 <= nums[i] <= 1000',
 'Use prefix sums with a hash map counting how many times each prefix sum has occurred. For each prefix sum S, add count[S-k] to the answer.',
 '["Prefix sum + hashmap counts"]',
 '[{"input":"[1,1,1]\\n2","output":"2"}]',
 '{"python":"def subarraySum(nums, k):\\n    pass","javascript":"function subarraySum(nums, k){\\n}","java":"public int subarraySum(int[] nums, int k){\\n  return 0;\\n}","cpp":"int subarraySum(vector<int>& nums,int k){\\n  return 0;\\n}"}',
 'curated'),

-- Binary Search
('Search in Rotated Sorted Array', 'search-in-rotated-sorted-array',
 'There is an integer array nums sorted in ascending order and rotated. Given nums and target, return its index, or -1 if not found.',
 'medium',
 '["Binary Search","Arrays"]',
 '["Amazon","Microsoft"]',
 '[{"input":"nums=[4,5,6,7,0,1,2], target=0","output":"4"}]',
 '1 <= nums.length <= 5000\nAll values are unique.',
 'Binary search by identifying the sorted half each step. Decide whether the target lies in the sorted half; narrow range accordingly.',
 '["Binary search using sorted-half logic"]',
 '[{"input":"[4,5,6,7,0,1,2]\\n0","output":"4"}]',
 '{"python":"def search(nums, target):\\n    pass","javascript":"function search(nums, target){\\n}","java":"public int search(int[] nums, int target){\\n  return -1;\\n}","cpp":"int search(vector<int>& nums,int target){\\n  return -1;\\n}"}',
 'curated'),

('Find Minimum in Rotated Sorted Array', 'find-minimum-in-rotated-sorted-array',
 'Given a rotated sorted array nums with unique elements, return the minimum element.',
 'medium',
 '["Binary Search","Arrays"]',
 '["Google","Amazon"]',
 '[{"input":"nums=[3,4,5,1,2]","output":"1"},{"input":"nums=[4,5,6,7,0,1,2]","output":"0"}]',
 '1 <= nums.length <= 5000\nAll values are unique.',
 'Binary search comparing mid with right. If nums[mid] > nums[right], min is to the right; otherwise it is in left including mid.',
 '["Binary search on rotation pivot"]',
 '[{"input":"[3,4,5,1,2]","output":"1"}]',
 '{"python":"def findMin(nums):\\n    pass","javascript":"function findMin(nums){\\n}","java":"public int findMin(int[] nums){\\n  return 0;\\n}","cpp":"int findMin(vector<int>& nums){\\n  return 0;\\n}"}',
 'curated'),

('Search a 2D Matrix', 'search-a-2d-matrix',
 'You are given an m x n matrix where each row is sorted and the first integer of each row is greater than the last integer of the previous row. Determine if target exists in the matrix.',
 'medium',
 '["Binary Search","Arrays"]',
 '["Amazon","Google"]',
 '[{"input":"matrix=[[1,3,5,7],[10,11,16,20],[23,30,34,60]], target=3","output":"true"}]',
 'm,n >= 1\nRows sorted; row0 < row1 invariant.',
 'Treat the matrix as a flattened sorted array of length m*n and binary search using index -> (row, col).',
 '["Binary search on flattened index"]',
 '[{"input":"[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\\n3","output":"true"}]',
 '{"python":"def searchMatrix(matrix, target):\\n    pass","javascript":"function searchMatrix(matrix, target){\\n}","java":"public boolean searchMatrix(int[][] matrix, int target){\\n  return false;\\n}","cpp":"bool searchMatrix(vector<vector<int>>& matrix,int target){\\n  return false;\\n}"}',
 'curated'),

-- Strings
('Valid Palindrome', 'valid-palindrome',
 'Given a string s, return true if it is a palindrome after converting to lowercase and removing all non-alphanumeric characters.',
 'easy',
 '["Strings","Two Pointers"]',
 '["Meta","Amazon"]',
 '[{"input":"s=\\"A man, a plan, a canal: Panama\\"","output":"true"},{"input":"s=\\"race a car\\"","output":"false"}]',
 '1 <= s.length <= 2e5',
 'Use two pointers from both ends. Skip non-alphanumeric; compare lowercase characters.',
 '["Two pointers with filtering"]',
 '[{"input":"A man, a plan, a canal: Panama","output":"true"}]',
 '{"python":"def isPalindrome(s):\\n    pass","javascript":"function isPalindrome(s){\\n}","java":"public boolean isPalindrome(String s){\\n  return false;\\n}","cpp":"bool isPalindrome(string s){\\n  return false;\\n}"}',
 'curated'),

('Group Anagrams', 'group-anagrams',
 'Given an array of strings strs, group the anagrams together.',
 'medium',
 '["Strings","Hashing"]',
 '["Amazon","Meta"]',
 '[{"input":"strs=[\\"eat\\",\\"tea\\",\\"tan\\",\\"ate\\",\\"nat\\",\\"bat\\"]","output":"[[\\"eat\\",\\"tea\\",\\"ate\\"],[\\"tan\\",\\"nat\\"],[\\"bat\\"]]"}]',
 '1 <= strs.length <= 1e4\n0 <= strs[i].length <= 100',
 'Use a canonical key for each word (sorted letters or 26-count signature). Map key -> list of words.',
 '["Hash map keyed by signature"]',
 '[{"input":"[\\\"eat\\\",\\\"tea\\\",\\\"tan\\\",\\\"ate\\\",\\\"nat\\\",\\\"bat\\\"]","output":"[[\\\"eat\\\",\\\"tea\\\",\\\"ate\\\"],[\\\"tan\\\",\\\"nat\\\"],[\\\"bat\\\"]]"}]',
 '{"python":"def groupAnagrams(strs):\\n    pass","javascript":"function groupAnagrams(strs){\\n}","java":"public List<List<String>> groupAnagrams(String[] strs){\\n  return null;\\n}","cpp":"vector<vector<string>> groupAnagrams(vector<string>& strs){\\n}"}',
 'curated'),

('Longest Palindromic Substring', 'longest-palindromic-substring',
 'Given a string s, return the longest palindromic substring in s.',
 'medium',
 '["Strings"]',
 '["Amazon","Google"]',
 '[{"input":"s=\\"babad\\"","output":"\\"bab\\""},{"input":"s=\\"cbbd\\"","output":"\\"bb\\""}]',
 '1 <= s.length <= 1000',
 'Expand around each possible center (odd and even). Track the maximum length palindrome found.',
 '["Expand around center"]',
 '[{"input":"babad","output":"bab"}]',
 '{"python":"def longestPalindrome(s):\\n    pass","javascript":"function longestPalindrome(s){\\n}","java":"public String longestPalindrome(String s){\\n  return \\"\\";\\n}","cpp":"string longestPalindrome(string s){\\n  return \\"\\";\\n}"}',
 'curated'),

('Longest Repeating Character Replacement', 'longest-repeating-character-replacement',
 'Given a string s and an integer k, you can replace at most k characters. Return the length of the longest substring containing the same letter after replacements.',
 'medium',
 '["Strings","Sliding Window"]',
 '["Amazon","Meta"]',
 '[{"input":"s=\\"AABABBA\\", k=1","output":"4"}]',
 '1 <= s.length <= 1e5',
 'Sliding window with counts of letters. Keep track of max frequency in the window; shrink while windowLen - maxFreq > k.',
 '["Sliding window with max frequency"]',
 '[{"input":"AABABBA\\n1","output":"4"}]',
 '{"python":"def characterReplacement(s, k):\\n    pass","javascript":"function characterReplacement(s, k){\\n}","java":"public int characterReplacement(String s, int k){\\n  return 0;\\n}","cpp":"int characterReplacement(string s,int k){\\n  return 0;\\n}"}',
 'curated'),

-- Linked List
('Merge Two Sorted Lists', 'merge-two-sorted-lists',
 'You are given the heads of two sorted linked lists. Merge them into one sorted list and return the head.',
 'easy',
 '["Linked List"]',
 '["Amazon","Microsoft"]',
 '[{"input":"l1=[1,2,4], l2=[1,3,4]","output":"[1,1,2,3,4,4]"}]',
 '0 <= n,m <= 50',
 'Use a dummy head and iteratively pick the smaller node from the two lists, advancing pointers until one ends.',
 '["Dummy head + two pointers"]',
 '[{"input":"[1,2,4]\\n[1,3,4]","output":"[1,1,2,3,4,4]"}]',
 '{"python":"def mergeTwoLists(l1, l2):\\n    pass","javascript":"function mergeTwoLists(l1, l2){\\n}","java":"public ListNode mergeTwoLists(ListNode l1, ListNode l2){\\n  return null;\\n}","cpp":"ListNode* mergeTwoLists(ListNode* l1, ListNode* l2){\\n  return nullptr;\\n}"}',
 'curated'),

('Remove Nth Node From End of List', 'remove-nth-node-from-end-of-list',
 'Given the head of a linked list, remove the nth node from the end of the list and return its head.',
 'medium',
 '["Linked List","Two Pointers"]',
 '["Amazon","Meta"]',
 '[{"input":"head=[1,2,3,4,5], n=2","output":"[1,2,3,5]"}]',
 '1 <= n <= length of list',
 'Two pointers with a gap of n. Move both until fast reaches end; remove slow.next.',
 '["Two pointers with n-gap"]',
 '[{"input":"[1,2,3,4,5]\\n2","output":"[1,2,3,5]"}]',
 '{"python":"def removeNthFromEnd(head, n):\\n    pass","javascript":"function removeNthFromEnd(head, n){\\n}","java":"public ListNode removeNthFromEnd(ListNode head, int n){\\n  return null;\\n}","cpp":"ListNode* removeNthFromEnd(ListNode* head,int n){\\n  return nullptr;\\n}"}',
 'curated'),

('Add Two Numbers', 'add-two-numbers',
 'You are given two non-empty linked lists representing two non-negative integers in reverse order. Add the two numbers and return the sum as a linked list.',
 'medium',
 '["Linked List"]',
 '["Amazon","Microsoft"]',
 '[{"input":"l1=[2,4,3], l2=[5,6,4]","output":"[7,0,8]"}]',
 'Each list has length >= 1',
 'Simulate addition with carry. Traverse both lists, add digits plus carry, append new node with digit and update carry.',
 '["Digit-by-digit addition with carry"]',
 '[{"input":"[2,4,3]\\n[5,6,4]","output":"[7,0,8]"}]',
 '{"python":"def addTwoNumbers(l1, l2):\\n    pass","javascript":"function addTwoNumbers(l1, l2){\\n}","java":"public ListNode addTwoNumbers(ListNode l1, ListNode l2){\\n  return null;\\n}","cpp":"ListNode* addTwoNumbers(ListNode* l1, ListNode* l2){\\n  return nullptr;\\n}"}',
 'curated'),

('Reorder List', 'reorder-list',
 'Given the head of a singly linked list L0→L1→…→Ln-1→Ln, reorder it to L0→Ln→L1→Ln-1→L2→Ln-2→… in-place.',
 'medium',
 '["Linked List"]',
 '["Amazon","Meta"]',
 '[{"input":"head=[1,2,3,4]","output":"[1,4,2,3]"}]',
 '1 <= n <= 5e4',
 'Find middle, reverse second half, then merge the two halves alternating nodes.',
 '["Split, reverse second half, merge alternately"]',
 '[{"input":"[1,2,3,4]","output":"[1,4,2,3]"}]',
 '{"python":"def reorderList(head):\\n    pass","javascript":"function reorderList(head){\\n}","java":"public void reorderList(ListNode head){\\n}","cpp":"void reorderList(ListNode* head){\\n}"}',
 'curated'),

-- Stack & Queue
('Min Stack', 'min-stack',
 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.',
 'medium',
 '["Stack & Queue"]',
 '["Amazon","Google"]',
 '[{"input":"operations=[\\"MinStack\\",\\"push\\",\\"push\\",\\"getMin\\",\\"pop\\",\\"top\\",\\"getMin\\"], values=[[],[-2],[0],[],[],[],[]]","output":"[null,null,null,-2,null,0,-2]"}]',
 'Operations up to 3e4',
 'Maintain a second stack storing the running minimum at each depth (or store pairs (val, minSoFar)).',
 '["Aux stack for mins"]',
 '[{"input":"push -2\\npush 0\\ngetMin","output":"-2"}]',
 '{"python":"class MinStack:\\n    def __init__(self):\\n        pass","javascript":"class MinStack {\\n  constructor(){}\\n}","java":"class MinStack {\\n  public MinStack(){}\\n}","cpp":"class MinStack {\\n};"}',
 'curated'),

('Daily Temperatures', 'daily-temperatures',
 'Given an array of temperatures, return an array answer where answer[i] is the number of days you have to wait after day i to get a warmer temperature. If none, answer[i]=0.',
 'medium',
 '["Stack & Queue","Arrays"]',
 '["Amazon","Meta"]',
 '[{"input":"temperatures=[73,74,75,71,69,72,76,73]","output":"[1,1,4,2,1,1,0,0]"}]',
 '1 <= temperatures.length <= 1e5',
 'Use a monotonic decreasing stack of indices. When a warmer temp appears, pop indices and set their answer as the distance.',
 '["Monotonic stack of indices"]',
 '[{"input":"[73,74,75,71,69,72,76,73]","output":"[1,1,4,2,1,1,0,0]"}]',
 '{"python":"def dailyTemperatures(temperatures):\\n    pass","javascript":"function dailyTemperatures(temperatures){\\n}","java":"public int[] dailyTemperatures(int[] temperatures){\\n  return null;\\n}","cpp":"vector<int> dailyTemperatures(vector<int>& t){\\n}"}',
 'curated'),

('Evaluate Reverse Polish Notation', 'evaluate-reverse-polish-notation',
 'Evaluate the value of an arithmetic expression in Reverse Polish Notation.',
 'medium',
 '["Stack & Queue"]',
 '["Amazon","Google"]',
 '[{"input":"tokens=[\\"2\\",\\"1\\",\\"+\\",\\"3\\",\\"*\\" ]","output":"9"}]',
 '1 <= tokens.length <= 1e4',
 'Use a stack. For numbers push; for an operator pop two operands, apply operator, and push result.',
 '["Stack-based evaluation"]',
 '[{"input":"[\\\"2\\\",\\\"1\\\",\\\"+\\\",\\\"3\\\",\\\"*\\\"]","output":"9"}]',
 '{"python":"def evalRPN(tokens):\\n    pass","javascript":"function evalRPN(tokens){\\n}","java":"public int evalRPN(String[] tokens){\\n  return 0;\\n}","cpp":"int evalRPN(vector<string>& tokens){\\n  return 0;\\n}"}',
 'curated'),

-- Recursion / Backtracking
('Generate Parentheses', 'generate-parentheses',
 'Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.',
 'medium',
 '["Recursion"]',
 '["Google","Amazon"]',
 '[{"input":"n=3","output":"[\\"((()))\\",\\"(()())\\",\\"(())()\\",\\"()(())\\",\\"()()()\\"]"}]',
 '1 <= n <= 8',
 'Backtracking: build string while tracking counts of open/close used. You can add an open if open<n, and close if close<open.',
 '["Backtrack with open/close counters"]',
 '[{"input":"3","output":"[\\\"((()))\\\",\\\"(()())\\\",\\\"(())()\\\",\\\"()(())\\\",\\\"()()()\\\"]"}]',
 '{"python":"def generateParenthesis(n):\\n    pass","javascript":"function generateParenthesis(n){\\n}","java":"public List<String> generateParenthesis(int n){\\n  return null;\\n}","cpp":"vector<string> generateParenthesis(int n){\\n}"}',
 'curated'),

('Subsets', 'subsets',
 'Given an integer array nums of unique elements, return all possible subsets (the power set).',
 'medium',
 '["Recursion","Arrays"]',
 '["Amazon","Meta"]',
 '[{"input":"nums=[1,2,3]","output":"[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"}]',
 '1 <= nums.length <= 10',
 'Backtracking: at each index, choose to include or exclude the element. Collect current subset when you reach the end.',
 '["Backtracking include/exclude"]',
 '[{"input":"[1,2,3]","output":"[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"}]',
 '{"python":"def subsets(nums):\\n    pass","javascript":"function subsets(nums){\\n}","java":"public List<List<Integer>> subsets(int[] nums){\\n  return null;\\n}","cpp":"vector<vector<int>> subsets(vector<int>& nums){\\n}"}',
 'curated'),

('Permutations', 'permutations',
 'Given an array nums of distinct integers, return all possible permutations.',
 'medium',
 '["Recursion","Arrays"]',
 '["Google","Amazon"]',
 '[{"input":"nums=[1,2,3]","output":"[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}]',
 '1 <= nums.length <= 6',
 'Backtracking: build a current permutation; at each step, try an unused number, mark it used, recurse, then undo.',
 '["Backtracking with used set"]',
 '[{"input":"[1,2,3]","output":"[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}]',
 '{"python":"def permute(nums):\\n    pass","javascript":"function permute(nums){\\n}","java":"public List<List<Integer>> permute(int[] nums){\\n  return null;\\n}","cpp":"vector<vector<int>> permute(vector<int>& nums){\\n}"}',
 'curated'),

('Combination Sum', 'combination-sum',
 'Given an array of distinct integers candidates and a target integer target, return all unique combinations where the chosen numbers sum to target. You may reuse numbers.',
 'medium',
 '["Recursion","Arrays"]',
 '["Amazon","Google"]',
 '[{"input":"candidates=[2,3,6,7], target=7","output":"[[2,2,3],[7]]"}]',
 '1 <= candidates.length <= 30\n1 <= candidates[i] <= 200',
 'Backtracking with an index: choose current candidate 0..k times while not exceeding target, recurse with same index for reuse, and advance index to avoid duplicates.',
 '["Backtracking with pruning on remaining sum"]',
 '[{"input":"[2,3,6,7]\\n7","output":"[[2,2,3],[7]]"}]',
 '{"python":"def combinationSum(candidates, target):\\n    pass","javascript":"function combinationSum(candidates, target){\\n}","java":"public List<List<Integer>> combinationSum(int[] candidates, int target){\\n  return null;\\n}","cpp":"vector<vector<int>> combinationSum(vector<int>& candidates,int target){\\n}"}',
 'curated'),

-- Trees
('Maximum Depth of Binary Tree', 'maximum-depth-of-binary-tree',
 'Given the root of a binary tree, return its maximum depth.',
 'easy',
 '["Trees","Recursion"]',
 '["Amazon","Google"]',
 '[{"input":"root=[3,9,20,null,null,15,7]","output":"3"}]',
 '0 <= number of nodes <= 1e4',
 'Use DFS recursion: depth(node) = 1 + max(depth(left), depth(right)). Base case null -> 0.',
 '["DFS recursion"]',
 '[{"input":"[3,9,20,null,null,15,7]","output":"3"}]',
 '{"python":"def maxDepth(root):\\n    pass","javascript":"function maxDepth(root){\\n}","java":"public int maxDepth(TreeNode root){\\n  return 0;\\n}","cpp":"int maxDepth(TreeNode* root){\\n  return 0;\\n}"}',
 'curated'),

('Invert Binary Tree', 'invert-binary-tree',
 'Given the root of a binary tree, invert the tree and return its root.',
 'easy',
 '["Trees","Recursion"]',
 '["Google","Amazon"]',
 '[{"input":"root=[4,2,7,1,3,6,9]","output":"[4,7,2,9,6,3,1]"}]',
 '0 <= number of nodes <= 100',
 'Recursively swap left and right children at every node (or do iterative BFS swapping).',
 '["Swap children recursively"]',
 '[{"input":"[4,2,7,1,3,6,9]","output":"[4,7,2,9,6,3,1]"}]',
 '{"python":"def invertTree(root):\\n    pass","javascript":"function invertTree(root){\\n}","java":"public TreeNode invertTree(TreeNode root){\\n  return null;\\n}","cpp":"TreeNode* invertTree(TreeNode* root){\\n  return nullptr;\\n}"}',
 'curated'),

('Binary Tree Level Order Traversal', 'binary-tree-level-order-traversal',
 'Given the root of a binary tree, return the level order traversal of its nodes’ values (left to right, level by level).',
 'medium',
 '["Trees","Stack & Queue"]',
 '["Amazon","Microsoft"]',
 '[{"input":"root=[3,9,20,null,null,15,7]","output":"[[3],[9,20],[15,7]]"}]',
 '0 <= number of nodes <= 2000',
 'Use BFS with a queue. For each level, process current queue length nodes and collect values.',
 '["BFS by levels"]',
 '[{"input":"[3,9,20,null,null,15,7]","output":"[[3],[9,20],[15,7]]"}]',
 '{"python":"def levelOrder(root):\\n    pass","javascript":"function levelOrder(root){\\n}","java":"public List<List<Integer>> levelOrder(TreeNode root){\\n  return null;\\n}","cpp":"vector<vector<int>> levelOrder(TreeNode* root){\\n}"}',
 'curated'),

('Validate Binary Search Tree', 'validate-binary-search-tree',
 'Given the root of a binary tree, determine if it is a valid binary search tree (BST).',
 'medium',
 '["Trees"]',
 '["Amazon","Google"]',
 '[{"input":"root=[2,1,3]","output":"true"},{"input":"root=[5,1,4,null,null,3,6]","output":"false"}]',
 'The number of nodes is in the range [1, 1e4].',
 'DFS with bounds: each node value must be strictly between (low, high). Recurse left with high=node.val and right with low=node.val.',
 '["DFS with min/max bounds"]',
 '[{"input":"[2,1,3]","output":"true"}]',
 '{"python":"def isValidBST(root):\\n    pass","javascript":"function isValidBST(root){\\n}","java":"public boolean isValidBST(TreeNode root){\\n  return false;\\n}","cpp":"bool isValidBST(TreeNode* root){\\n  return false;\\n}"}',
 'curated'),

('Diameter of Binary Tree', 'diameter-of-binary-tree',
 'Given the root of a binary tree, return the length of the diameter of the tree (number of edges on the longest path between any two nodes).',
 'easy',
 '["Trees","Recursion"]',
 '["Amazon","Meta"]',
 '[{"input":"root=[1,2,3,4,5]","output":"3"}]',
 '0 <= number of nodes <= 1e4',
 'Compute height of subtrees with DFS. For each node, candidate diameter is leftHeight + rightHeight. Track global maximum.',
 '["DFS height; update global max"]',
 '[{"input":"[1,2,3,4,5]","output":"3"}]',
 '{"python":"def diameterOfBinaryTree(root):\\n    pass","javascript":"function diameterOfBinaryTree(root){\\n}","java":"public int diameterOfBinaryTree(TreeNode root){\\n  return 0;\\n}","cpp":"int diameterOfBinaryTree(TreeNode* root){\\n  return 0;\\n}"}',
 'curated'),

-- Graphs
('Number of Islands', 'number-of-islands',
 'Given an m x n 2D grid of "1"s (land) and "0"s (water), return the number of islands.',
 'medium',
 '["Graphs"]',
 '["Amazon","Google"]',
 '[{"input":"grid=[[\\"1\\",\\"1\\",\\"0\\"],[\\"1\\",\\"1\\",\\"0\\"],[\\"0\\",\\"0\\",\\"1\\"]]","output":"2"}]',
 'm,n <= 300',
 'Traverse grid; when you find unvisited land, run DFS/BFS to mark the entire island visited and increment count.',
 '["DFS/BFS flood fill"]',
 '[{"input":"[[\\\"1\\\",\\\"1\\\",\\\"0\\\"],[\\\"1\\\",\\\"1\\\",\\\"0\\\"],[\\\"0\\\",\\\"0\\\",\\\"1\\\"]]","output":"2"}]',
 '{"python":"def numIslands(grid):\\n    pass","javascript":"function numIslands(grid){\\n}","java":"public int numIslands(char[][] grid){\\n  return 0;\\n}","cpp":"int numIslands(vector<vector<char>>& grid){\\n  return 0;\\n}"}',
 'curated'),

('Course Schedule', 'course-schedule',
 'There are numCourses courses labeled 0..numCourses-1. prerequisites[i] = [a,b] means you must take b before a. Return true if you can finish all courses.',
 'medium',
 '["Graphs"]',
 '["Google","Amazon"]',
 '[{"input":"numCourses=2, prerequisites=[[1,0]]","output":"true"},{"input":"numCourses=2, prerequisites=[[1,0],[0,1]]","output":"false"}]',
 '1 <= numCourses <= 2000',
 'Model as directed graph and detect cycles via DFS coloring or Kahn’s topological sort. If a cycle exists, cannot finish.',
 '["Topological sort / cycle detection"]',
 '[{"input":"2\\n[[1,0],[0,1]]","output":"false"}]',
 '{"python":"def canFinish(numCourses, prerequisites):\\n    pass","javascript":"function canFinish(numCourses, prerequisites){\\n}","java":"public boolean canFinish(int numCourses, int[][] prerequisites){\\n  return false;\\n}","cpp":"bool canFinish(int numCourses, vector<vector<int>>& prerequisites){\\n  return false;\\n}"}',
 'curated'),

('Rotting Oranges', 'rotting-oranges',
 'You are given a grid where 0=empty, 1=fresh orange, 2=rotten orange. Each minute, fresh oranges adjacent to rotten become rotten. Return minutes until no fresh remain, or -1.',
 'medium',
 '["Graphs","Stack & Queue"]',
 '["Amazon","Microsoft"]',
 '[{"input":"grid=[[2,1,1],[1,1,0],[0,1,1]]","output":"4"}]',
 'm,n <= 100',
 'Multi-source BFS: enqueue all rotten oranges initially with time=0. BFS spreads rot; track minutes and remaining fresh.',
 '["Multi-source BFS on grid"]',
 '[{"input":"[[2,1,1],[1,1,0],[0,1,1]]","output":"4"}]',
 '{"python":"def orangesRotting(grid):\\n    pass","javascript":"function orangesRotting(grid){\\n}","java":"public int orangesRotting(int[][] grid){\\n  return 0;\\n}","cpp":"int orangesRotting(vector<vector<int>>& grid){\\n  return 0;\\n}"}',
 'curated'),

-- Dynamic Programming
('Climbing Stairs', 'climbing-stairs',
 'You are climbing a staircase. It takes n steps to reach the top. Each time you can climb 1 or 2 steps. Return number of distinct ways.',
 'easy',
 '["Dynamic Programming"]',
 '["Amazon","Google"]',
 '[{"input":"n=3","output":"3"}]',
 '1 <= n <= 45',
 'Classic Fibonacci DP: ways[i] = ways[i-1] + ways[i-2]. Use two variables for O(1) space.',
 '["Fibonacci DP"]',
 '[{"input":"3","output":"3"}]',
 '{"python":"def climbStairs(n):\\n    pass","javascript":"function climbStairs(n){\\n}","java":"public int climbStairs(int n){\\n  return 0;\\n}","cpp":"int climbStairs(int n){\\n  return 0;\\n}"}',
 'curated'),

('House Robber', 'house-robber',
 'You are given an integer array nums representing the amount of money of each house. You cannot rob adjacent houses. Return the maximum amount.',
 'medium',
 '["Dynamic Programming"]',
 '["Amazon","Google"]',
 '[{"input":"nums=[2,7,9,3,1]","output":"12"}]',
 '1 <= nums.length <= 100',
 'DP with two states: at each house, best = max(prevBest, prevPrevBest + nums[i]). Track rolling values.',
 '["Rolling DP: take vs skip"]',
 '[{"input":"[2,7,9,3,1]","output":"12"}]',
 '{"python":"def rob(nums):\\n    pass","javascript":"function rob(nums){\\n}","java":"public int rob(int[] nums){\\n  return 0;\\n}","cpp":"int rob(vector<int>& nums){\\n  return 0;\\n}"}',
 'curated'),

('Coin Change', 'coin-change',
 'Given coins and amount, return the fewest number of coins needed to make up amount. If impossible, return -1.',
 'medium',
 '["Dynamic Programming"]',
 '["Amazon","Microsoft"]',
 '[{"input":"coins=[1,2,5], amount=11","output":"3"},{"input":"coins=[2], amount=3","output":"-1"}]',
 '0 <= amount <= 1e4',
 'Bottom-up DP where dp[x] is min coins to make x. Initialize dp[0]=0 and relax with each coin.',
 '["DP over amounts"]',
 '[{"input":"[1,2,5]\\n11","output":"3"}]',
 '{"python":"def coinChange(coins, amount):\\n    pass","javascript":"function coinChange(coins, amount){\\n}","java":"public int coinChange(int[] coins, int amount){\\n  return -1;\\n}","cpp":"int coinChange(vector<int>& coins,int amount){\\n  return -1;\\n}"}',
 'curated'),

('Longest Increasing Subsequence', 'longest-increasing-subsequence',
 'Given an integer array nums, return the length of the longest strictly increasing subsequence.',
 'medium',
 '["Dynamic Programming","Binary Search"]',
 '["Amazon","Google"]',
 '[{"input":"nums=[10,9,2,5,3,7,101,18]","output":"4"}]',
 '1 <= nums.length <= 2500',
 'Use patience sorting idea: maintain an array tails where tails[len] is the minimum possible tail of an increasing subsequence of length len+1. Binary search to place each number.',
 '["Tails array + binary search"]',
 '[{"input":"[10,9,2,5,3,7,101,18]","output":"4"}]',
 '{"python":"def lengthOfLIS(nums):\\n    pass","javascript":"function lengthOfLIS(nums){\\n}","java":"public int lengthOfLIS(int[] nums){\\n  return 0;\\n}","cpp":"int lengthOfLIS(vector<int>& nums){\\n  return 0;\\n}"}',
 'curated'),

-- Greedy
('Jump Game', 'jump-game',
 'You are given an integer array nums where nums[i] is maximum jump length from i. Return true if you can reach the last index.',
 'medium',
 '["Greedy","Arrays"]',
 '["Amazon","Google"]',
 '[{"input":"nums=[2,3,1,1,4]","output":"true"},{"input":"nums=[3,2,1,0,4]","output":"false"}]',
 '1 <= nums.length <= 1e4',
 'Greedy: track the farthest reachable index as you scan. If you ever reach an index beyond farthest, you fail.',
 '["Track farthest reachable"]',
 '[{"input":"[2,3,1,1,4]","output":"true"}]',
 '{"python":"def canJump(nums):\\n    pass","javascript":"function canJump(nums){\\n}","java":"public boolean canJump(int[] nums){\\n  return false;\\n}","cpp":"bool canJump(vector<int>& nums){\\n  return false;\\n}"}',
 'curated'),

-- Bit Manipulation
('Single Number', 'single-number',
 'Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.',
 'easy',
 '["Bit Manipulation","Arrays"]',
 '["Amazon","Google"]',
 '[{"input":"nums=[4,1,2,1,2]","output":"4"}]',
 '1 <= nums.length <= 3e4',
 'Use XOR: a^a=0 and a^0=a. XOR all elements to cancel pairs and get the unique element.',
 '["XOR all numbers"]',
 '[{"input":"[4,1,2,1,2]","output":"4"}]',
 '{"python":"def singleNumber(nums):\\n    pass","javascript":"function singleNumber(nums){\\n}","java":"public int singleNumber(int[] nums){\\n  return 0;\\n}","cpp":"int singleNumber(vector<int>& nums){\\n  return 0;\\n}"}',
 'curated'),

('Number of 1 Bits', 'number-of-1-bits',
 'Write a function that takes an unsigned integer and returns the number of 1 bits (Hamming weight).',
 'easy',
 '["Bit Manipulation"]',
 '["Amazon","Microsoft"]',
 '[{"input":"n=11","output":"3"}]',
 '0 <= n < 2^32',
 'Use bit tricks: repeatedly do n &= (n-1) to clear the lowest set bit and count iterations.',
 '["n &= (n-1) loop"]',
 '[{"input":"11","output":"3"}]',
 '{"python":"def hammingWeight(n):\\n    pass","javascript":"function hammingWeight(n){\\n}","java":"public int hammingWeight(int n){\\n  return 0;\\n}","cpp":"int hammingWeight(uint32_t n){\\n  return 0;\\n}"}',
 'curated'),

('Counting Bits', 'counting-bits',
 'Given an integer n, return an array ans where ans[i] is the number of 1s in the binary representation of i for 0 <= i <= n.',
 'easy',
 '["Bit Manipulation","Dynamic Programming"]',
 '["Google","Amazon"]',
 '[{"input":"n=5","output":"[0,1,1,2,1,2]"}]',
 '0 <= n <= 1e5',
 'DP: ans[i] = ans[i >> 1] + (i & 1). Build from 0..n.',
 '["DP using right shift"]',
 '[{"input":"5","output":"[0,1,1,2,1,2]"}]',
 '{"python":"def countBits(n):\\n    pass","javascript":"function countBits(n){\\n}","java":"public int[] countBits(int n){\\n  return null;\\n}","cpp":"vector<int> countBits(int n){\\n}"}',
 'curated');
